language: ruby
sudo: false
cache: bundler
rvm:
- 2.1
script: bundle exec middleman build
deploy:
- provider: s3
  access_key_id: AKIAJRN7WFNBVEFDWQTQ
  secret_access_key:
    secure: "ThQ9bZmOxGEGW/BLFuVWOk6eHapQd3q9xMyi6PAAEHVkiEAaedSJcstLMHxg2vlm2/fQDhlw4oOA4/bZVsXQ4X7bBtGvhCB5pzAezHZRfcosnlA3ADqie1tb0oIZX2Cg1ssLbxJCiyTTaaiJNVoSoh0dhDTAi23Q0JBvMQi9xMg="
  bucket: semicolon.fm
  local-dir: build
  skip_cleanup: true
  on:
    branch: master
ranch: master


